alter table CEUM_MESSAGE add constraint FK_CEUM_MESSAGE_MESSAGE_TEXT_ID foreign key (MESSAGE_TEXT_ID) references CEUM_MESSAGE_TEXT(ID);
create index IDX_CEUM_MESSAGE_MESSAGE_TEXT on CEUM_MESSAGE (MESSAGE_TEXT_ID);
